### ISSUE TITLE
Summary of bugs on Aquaris X

### ISSUE THREAD

**Issue by xblax** [brinlyau/android_device_bq_bardock#3]
I tested a LineageOS build based on the sources in this repository. I guess you're aware that there are still some major bugs - but maybe this feedback can help you. Dmesg and logcat attached.

Speaker(-)
Headset(+) works but no indication of plugged in Headset
Built-in Microphone (+)

Camera(-) crashes on start

> 10-05 18:22:54.517  5795  5878 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
10-05 18:22:54.517  5795  5878 E AndroidRuntime: Process: com.android.camera2, PID: 5795
10-05 18:22:54.517  5795  5878 E AndroidRuntime: java.lang.IllegalStateException
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at com.android.camera.settings.ResolutionSetting.getPictureSize(ResolutionSetting.java:165)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at com.android.camera.CaptureModule.openCameraAndStartPreview(CaptureModule.java:1363)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at com.android.camera.CaptureModule.-wrap8(CaptureModule.java)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at com.android.camera.CaptureModule$10.run(CaptureModule.java:653)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-05 18:22:54.517  5795  5878 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:761)

Fingerprint reader(-) maybe not working because fringerprintd service not started?

Telephone (+)
WIFI (-)

dmesg:
> [   60.969284] ------------[ cut here ]------------
[   60.969457] WARNING: CPU: 6 PID: 2897 at ../../../../../../kernel/bq/msm8953/drivers/staging/prima/CORE/VOSS/src/vos_api.c:921 vos_start+0x208/0x508 [wlan]()
[   60.969461] Modules linked in: wlan(C+)
[   60.969471] CPU: 6 PID: 2897 Comm: WifiStateMachin Tainted: G        WC     3.18.31-perf-ge177b838789 #1
[   60.969474] Hardware name: Qualcomm Technologies, Inc. MSM8953 QRD SKU3 (DT)
[   60.969477] Call trace:
[   60.969487] [<ffffffc000089afc>] dump_backtrace+0x0/0x23c
[   60.969492] [<ffffffc000089d4c>] show_stack+0x14/0x1c
[   60.969499] [<ffffffc000c871c4>] dump_stack+0x80/0xa4
[   60.969505] [<ffffffc0000a2d90>] warn_slowpath_common+0x8c/0xb0
[   60.969509] [<ffffffc0000a2ecc>] warn_slowpath_null+0x18/0x20
[   60.969625] [<ffffffbffc198790>] vos_start+0x208/0x508 [wlan]
[   60.969700] [<ffffffbffc046ce0>] hdd_wlan_startup+0x8d8/0x14a0 [wlan]
[   60.969785] [<ffffffbffc446148>] init_module+0x148/0x1000 [wlan]
[   60.969791] [<ffffffc000082ae4>] do_one_initcall+0x18c/0x1a8
[   60.969797] [<ffffffc0001199f4>] load_module+0x1440/0x1ab0
[   60.969801] [<ffffffc00011a22c>] SyS_finit_module+0x94/0xbc
[   60.969804] ---[ end trace 3a05f0ff8df53b23 ]---
[   61.160155] wlan: driver load failure

logcat:
>10-05 18:56:04.451  1500  2897 D WifiHW  : finit_module for "/system/lib/modules/wlan.ko" failed: Operation not permitted
10-05 18:56:04.451  1500  2897 E WifiStateMachine: Failed to load driver
10-05 18:56:04.453  1500  1500 E WifiController: WifiControllerWifi turn on failed

Mobile Data (-) LTE and HSDPA works but no mobile data (see attached screenshot)
NFC (-) settings are missing, NFC test app does not work
Bluetooth (-) no devices found

ADB(+)
MicroSD(+)
MTP File Tansfer(+)
Encryption(+)

Right capacitive button opens launcher settings instead recent apps
Flickering of a red frame on screen (probably because strict mode is enabled by default)

![screenshot_20171005-190457](https://user-images.githubusercontent.com/9802544/31284172-1d354436-aab8-11e7-9e6c-e083a95faa0e.png)
![screenshot_20171005-190034](https://user-images.githubusercontent.com/9802544/31284255-4aaafd98-aab8-11e7-9254-1f29d13456e0.png)

[dmesg_bardock_lineagos_14.1_20171004-UNOFFICIAL.txt](https://github.com/brinlyau/android_device_bq_bardock/files/1363068/dmesg_bardock_lineagos_14.1_20171004-UNOFFICIAL.txt)
[logcat_bardock_lineagos_14.1_20171004-UNOFFICIAL.txt](https://github.com/brinlyau/android_device_bq_bardock/files/1363069/logcat_bardock_lineagos_14.1_20171004-UNOFFICIAL.txt)

**Comment by brinlyau** [comment]
I'm not supporting the X variant immediately, but please ping me on Hangouts or via an email/telegram and you can help me debug.
